// 主要日本株ローカルインデックス（日本語名検索用）
// コード → { 日本語名, 英語名(検索用) }
export const JP_STOCK_INDEX: Array<{ code: string; name: string; en: string }> = [
  // ── 半導体・半導体製造装置 ──────────────────────────────────────
  { code: '6920', name: 'レーザーテック',                     en: 'Lasertec' },
  { code: '8035', name: '東京エレクトロン',                   en: 'Tokyo Electron' },
  { code: '6857', name: 'アドバンテスト',                     en: 'Advantest' },
  { code: '6146', name: 'ディスコ',                          en: 'Disco' },
  { code: '7735', name: 'SCREENホールディングス',              en: 'SCREEN Holdings' },
  { code: '6723', name: 'ルネサスエレクトロニクス',            en: 'Renesas' },
  { code: '6963', name: 'ローム',                            en: 'Rohm' },
  { code: '285A', name: 'キオクシアホールディングス',           en: 'Kioxia Holdings' },
  { code: '148A', name: 'コクサイエレクトリック',              en: 'Kokusai Electric' },
  // ── 電子部品・精密機器 ────────────────────────────────────────
  { code: '6981', name: '村田製作所',                        en: 'Murata' },
  { code: '6594', name: 'ニデック',                          en: 'Nidec' },
  { code: '6762', name: 'TDK',                              en: 'TDK' },
  { code: '6971', name: '京セラ',                            en: 'Kyocera' },
  { code: '6861', name: 'キーエンス',                        en: 'Keyence' },
  { code: '6954', name: 'ファナック',                        en: 'Fanuc' },
  { code: '6479', name: 'ミネベアミツミ',                     en: 'MinebeaMitsumi' },
  { code: '6770', name: 'アルプスアルパイン',                  en: 'Alps Alpine' },
  { code: '6976', name: '太陽誘電',                          en: 'Taiyo Yuden' },
  { code: '6967', name: '新光電気工業',                       en: 'Shinko Electric' },
  { code: '4062', name: 'イビデン',                          en: 'Ibiden' },
  { code: '6988', name: '日東電工',                          en: 'Nitto Denko' },
  { code: '7915', name: 'NISSHA',                           en: 'Nissha' },
  { code: '6841', name: '横河電機',                          en: 'Yokogawa Electric' },
  { code: '6645', name: 'オムロン',                          en: 'Omron' },
  { code: '7741', name: 'HOYA',                             en: 'Hoya' },
  { code: '7733', name: 'オリンパス',                        en: 'Olympus' },
  { code: '4543', name: 'テルモ',                            en: 'Terumo' },
  { code: '6869', name: 'シスメックス',                       en: 'Sysmex' },
  // ── 総合電機・エレクトロニクス ──────────────────────────────────
  { code: '6758', name: 'ソニーグループ',                     en: 'Sony' },
  { code: '6752', name: 'パナソニック ホールディングス',        en: 'Panasonic' },
  { code: '6501', name: '日立製作所',                        en: 'Hitachi' },
  { code: '6502', name: '東芝',                              en: 'Toshiba' },
  { code: '6702', name: '富士通',                            en: 'Fujitsu' },
  { code: '6701', name: '日本電気',                          en: 'NEC' },
  { code: '6753', name: 'シャープ',                          en: 'Sharp' },
  { code: '6503', name: '三菱電機',                          en: 'Mitsubishi Electric' },
  { code: '6504', name: '富士電機',                          en: 'Fuji Electric' },
  { code: '6508', name: '明電舎',                            en: 'Meidensha' },
  { code: '6367', name: 'ダイキン工業',                       en: 'Daikin' },
  { code: '7751', name: 'キヤノン',                          en: 'Canon' },
  { code: '7752', name: 'リコー',                            en: 'Ricoh' },
  { code: '4901', name: '富士フイルムホールディングス',          en: 'Fujifilm' },
  // ── ケーブル・データセンター関連 ───────────────────────────────
  { code: '5803', name: 'フジクラ',                          en: 'Fujikura' },
  { code: '5801', name: '古河電気工業',                       en: 'Furukawa Electric' },
  { code: '5802', name: '住友電気工業',                       en: 'Sumitomo Electric' },
  // ── 自動車・モビリティ ──────────────────────────────────────────
  { code: '7203', name: 'トヨタ自動車',                       en: 'Toyota' },
  { code: '7267', name: '本田技研工業',                       en: 'Honda' },
  { code: '7201', name: '日産自動車',                        en: 'Nissan' },
  { code: '7270', name: 'SUBARU',                           en: 'Subaru' },
  { code: '7269', name: 'スズキ',                            en: 'Suzuki' },
  { code: '7211', name: '三菱自動車工業',                     en: 'Mitsubishi Motors' },
  { code: '7272', name: 'ヤマハ発動機',                       en: 'Yamaha Motor' },
  { code: '7261', name: 'マツダ',                            en: 'Mazda' },
  { code: '6902', name: 'デンソー',                          en: 'Denso' },
  { code: '7259', name: 'アイシン',                          en: 'Aisin' },
  { code: '6471', name: '日本精工',                          en: 'NSK' },
  { code: '5105', name: 'TOYO TIRE',                        en: 'Toyo Tire' },
  { code: '5108', name: 'ブリヂストン',                       en: 'Bridgestone' },
  // ── 通信・キャリア ────────────────────────────────────────────
  { code: '9984', name: 'ソフトバンクグループ',                en: 'SoftBank Group' },
  { code: '9434', name: 'ソフトバンク',                       en: 'SoftBank Corp' },
  { code: '9432', name: '日本電信電話',                       en: 'NTT' },
  { code: '9433', name: 'KDDI',                             en: 'KDDI' },
  { code: '9613', name: 'NTTデータグループ',                  en: 'NTT Data' },
  { code: '9437', name: 'NTTドコモ',                         en: 'NTT Docomo' },
  // ── IT・インターネット・ソフトウェア ────────────────────────────
  { code: '4689', name: 'LINEヤフー',                        en: 'LINEYahoo' },
  { code: '4755', name: '楽天グループ',                       en: 'Rakuten' },
  { code: '4751', name: 'サイバーエージェント',                en: 'CyberAgent' },
  { code: '4385', name: 'メルカリ',                          en: 'Mercari' },
  { code: '2413', name: 'エムスリー',                        en: 'M3' },
  { code: '3659', name: 'ネクソン',                          en: 'Nexon' },
  { code: '9449', name: 'GMOインターネットグループ',            en: 'GMO Internet' },
  { code: '4478', name: 'フリー',                            en: 'Freee' },
  { code: '4307', name: '野村総合研究所',                     en: 'NRI' },
  { code: '4684', name: 'オービック',                        en: 'Obic' },
  { code: '4704', name: 'トレンドマイクロ',                    en: 'Trend Micro' },
  { code: '9719', name: 'SCSK',                             en: 'SCSK' },
  { code: '4812', name: 'DTSホールディングス',                en: 'DTS Holdings' },
  { code: '3774', name: 'インターネットイニシアティブ',          en: 'IIJ' },
  { code: '3738', name: 'TIS',                              en: 'TIS' },
  { code: '4739', name: 'IT Holdings',                      en: 'ITbookHD' },
  { code: '9783', name: 'ベネッセホールディングス',             en: 'Benesse' },
  { code: '4565', name: 'そーせいグループ',                    en: 'Sosei Group' },
  { code: '3697', name: 'SHIFT',                            en: 'Shift' },
  { code: '4726', name: 'ソフトバンク・テクノロジー',           en: 'SoftBank Technology' },
  { code: '3923', name: 'ラクス',                            en: 'Rakus' },
  // ── 金融・銀行 ──────────────────────────────────────────────
  { code: '8306', name: '三菱UFJフィナンシャル・グループ',      en: 'MUFG' },
  { code: '8316', name: '三井住友フィナンシャルグループ',        en: 'SMFG' },
  { code: '8411', name: 'みずほフィナンシャルグループ',         en: 'Mizuho' },
  { code: '8309', name: '三井住友トラスト・ホールディングス',    en: 'Sumitomo Mitsui Trust' },
  { code: '8308', name: 'りそなホールディングス',               en: 'Resona' },
  { code: '8331', name: '千葉銀行',                          en: 'Chiba Bank' },
  { code: '8355', name: '静岡銀行',                          en: 'Shizuoka Bank' },
  { code: '8359', name: '八十二銀行',                        en: 'Hachijuni Bank' },
  { code: '8368', name: '百五銀行',                          en: 'Hyakugo Bank' },
  { code: '8382', name: '中国銀行',                          en: 'Chugoku Bank' },
  { code: '8332', name: '横浜銀行',                          en: 'Bank of Yokohama' },
  { code: '8377', name: 'ほくほくフィナンシャルグループ',        en: 'Hokuhoku FG' },
  { code: '8379', name: '広島銀行',                          en: 'Hiroshima Bank' },
  // ── 証券・資産運用 ───────────────────────────────────────────
  { code: '8604', name: '野村ホールディングス',                en: 'Nomura' },
  { code: '8601', name: '大和証券グループ本社',                en: 'Daiwa Securities' },
  { code: '8698', name: 'マネックスグループ',                  en: 'Monex' },
  { code: '8595', name: 'ジャフコグループ',                    en: 'Jafco' },
  { code: '8591', name: 'オリックス',                        en: 'Orix' },
  // ── 保険 ─────────────────────────────────────────────────
  { code: '8750', name: '第一生命保険',                       en: 'Dai-ichi Life' },
  { code: '8766', name: '東京海上ホールディングス',             en: 'Tokio Marine' },
  { code: '8725', name: 'MS&ADインシュアランスグループ',        en: 'MS&AD Insurance' },
  { code: '8630', name: 'SOMPOホールディングス',               en: 'SOMPO' },
  { code: '7181', name: 'かんぽ生命保険',                     en: 'Japan Post Insurance' },
  // ── 商社 ─────────────────────────────────────────────────
  { code: '8001', name: '伊藤忠商事',                        en: 'Itochu' },
  { code: '8031', name: '三井物産',                          en: 'Mitsui & Co' },
  { code: '8058', name: '三菱商事',                          en: 'Mitsubishi Corp' },
  { code: '8053', name: '住友商事',                          en: 'Sumitomo Corp' },
  { code: '8002', name: '丸紅',                              en: 'Marubeni' },
  { code: '8015', name: '豊田通商',                          en: 'Toyota Tsusho' },
  { code: '8016', name: 'オンワードホールディングス',           en: 'Onward' },
  // ── 小売・流通 ─────────────────────────────────────────────
  { code: '9983', name: 'ファーストリテイリング',               en: 'Fast Retailing' },
  { code: '8267', name: 'イオン',                            en: 'AEON' },
  { code: '3382', name: 'セブン&アイ・ホールディングス',        en: 'Seven & i' },
  { code: '2651', name: 'ローソン',                          en: 'Lawson' },
  { code: '8028', name: 'ファミリーマート',                    en: 'FamilyMart' },
  { code: '9843', name: 'ニトリホールディングス',               en: 'Nitori' },
  { code: '3086', name: 'J.フロント リテイリング',             en: 'J.Front Retailing' },
  { code: '8233', name: '高島屋',                            en: 'Takashimaya' },
  { code: '8252', name: '丸井グループ',                       en: 'Marui Group' },
  { code: '8270', name: 'ユニー・ファミリーマートHD',           en: 'Uny FamilyMart' },
  { code: '2698', name: 'キャンドゥ',                        en: 'Can Do' },
  { code: '7545', name: '西松屋チェーン',                     en: 'Nishimatsuya' },
  { code: '3099', name: '三越伊勢丹ホールディングス',           en: 'Isetan Mitsukoshi' },
  // ── 医薬品・バイオ ────────────────────────────────────────
  { code: '4502', name: '武田薬品工業',                       en: 'Takeda' },
  { code: '4503', name: 'アステラス製薬',                     en: 'Astellas' },
  { code: '4523', name: 'エーザイ',                          en: 'Eisai' },
  { code: '4568', name: '第一三共',                          en: 'Daiichi Sankyo' },
  { code: '4507', name: '塩野義製薬',                        en: 'Shionogi' },
  { code: '4519', name: '中外製薬',                          en: 'Chugai' },
  { code: '4578', name: '大塚ホールディングス',                en: 'Otsuka' },
  { code: '4506', name: '住友ファーマ',                       en: 'Sumitomo Pharma' },
  { code: '4151', name: '協和キリン',                        en: 'Kyowa Kirin' },
  { code: '4536', name: '参天製薬',                          en: 'Santen Pharma' },
  { code: '4539', name: '日本化薬',                          en: 'Nippon Kayaku' },
  { code: '4587', name: 'ペプチドリーム',                     en: 'PeptiDream' },
  { code: '4571', name: 'ナノキャリア',                       en: 'NanoCarrier' },
  // ── 医療機器・ヘルスケア ────────────────────────────────────
  { code: '7741', name: 'HOYA',                             en: 'Hoya' },
  { code: '4321', name: 'ケアネット',                        en: 'Carenet' },
  { code: '3831', name: 'メディア工房',                       en: 'Media Kobo' },
  // ── 素材・鉄鋼・非鉄 ─────────────────────────────────────
  { code: '5401', name: '日本製鉄',                          en: 'Nippon Steel' },
  { code: '5411', name: 'JFEホールディングス',                 en: 'JFE Holdings' },
  { code: '5406', name: '神戸製鋼所',                        en: 'Kobe Steel' },
  { code: '5707', name: '東邦亜鉛',                          en: 'Toho Zinc' },
  { code: '5713', name: '住友金属鉱山',                       en: 'Sumitomo Metal Mining' },
  { code: '5706', name: '三菱マテリアル',                     en: 'Mitsubishi Materials' },
  { code: '3436', name: 'SUMCO',                            en: 'SUMCO' },
  // ── 化学 ─────────────────────────────────────────────────
  { code: '4188', name: '三菱ケミカルグループ',                en: 'Mitsubishi Chemical' },
  { code: '4063', name: '信越化学工業',                       en: 'Shin-Etsu Chemical' },
  { code: '4004', name: 'AGC',                              en: 'AGC' },
  { code: '4005', name: '住友化学',                          en: 'Sumitomo Chemical' },
  { code: '4021', name: '日産化学',                          en: 'Nissan Chemical' },
  { code: '4183', name: '三井化学',                          en: 'Mitsui Chemicals' },
  { code: '4042', name: '東ソー',                            en: 'Tosoh' },
  { code: '4208', name: '宇部興産',                          en: 'Ube Industries' },
  // ── 重工業・機械 ───────────────────────────────────────────
  { code: '7011', name: '三菱重工業',                        en: 'Mitsubishi Heavy Industries' },
  { code: '7013', name: 'IHI',                              en: 'IHI' },
  { code: '6301', name: 'コマツ',                            en: 'Komatsu' },
  { code: '6326', name: 'クボタ',                            en: 'Kubota' },
  { code: '6302', name: '住友重機械工業',                     en: 'Sumitomo Heavy Industries' },
  { code: '6305', name: '日立建機',                          en: 'Hitachi Construction Machinery' },
  { code: '7004', name: '日立造船',                          en: 'Hitachi Zosen' },
  { code: '6361', name: '荏原製作所',                        en: 'Ebara' },
  // ── ゴム・タイヤ ─────────────────────────────────────────
  { code: '5101', name: '横浜ゴム',                          en: 'Yokohama Rubber' },
  { code: '5106', name: '東洋タイヤ',                        en: 'Toyo Tires' },
  // ── 不動産 ──────────────────────────────────────────────
  { code: '8801', name: '三井不動産',                        en: 'Mitsui Fudosan' },
  { code: '8802', name: '三菱地所',                          en: 'Mitsubishi Estate' },
  { code: '8804', name: '東京建物',                          en: 'Tokyo Tatemono' },
  { code: '8830', name: '住友不動産',                        en: 'Sumitomo Realty' },
  { code: '3003', name: 'ヒューリック',                       en: 'Hulic' },
  { code: '1925', name: '大和ハウス工業',                     en: 'Daiwa House' },
  { code: '1928', name: '積水ハウス',                        en: 'Sekisui House' },
  { code: '1808', name: '長谷工コーポレーション',              en: 'Haseko' },
  // ── 建設・ゼネコン ────────────────────────────────────────
  { code: '1803', name: '清水建設',                          en: 'Shimizu' },
  { code: '1812', name: '鹿島建設',                          en: 'Kajima' },
  { code: '1801', name: '大成建設',                          en: 'Taisei' },
  { code: '1802', name: '大林組',                            en: 'Obayashi' },
  // ── 食品・飲料 ─────────────────────────────────────────────
  { code: '2502', name: 'アサヒグループホールディングス',        en: 'Asahi' },
  { code: '2503', name: 'キリンホールディングス',               en: 'Kirin' },
  { code: '2802', name: '味の素',                            en: 'Ajinomoto' },
  { code: '2897', name: '日清食品ホールディングス',             en: 'Nissin' },
  { code: '2801', name: 'キッコーマン',                       en: 'Kikkoman' },
  { code: '2282', name: '日本ハム',                          en: 'Nippon Ham' },
  { code: '2269', name: '明治ホールディングス',                en: 'Meiji Holdings' },
  { code: '2871', name: 'ニチレイ',                          en: 'Nichirei' },
  { code: '2810', name: 'ハウス食品グループ本社',              en: 'House Foods' },
  { code: '2212', name: '山崎製パン',                        en: 'Yamazaki Baking' },
  // ── 外食 ─────────────────────────────────────────────────
  { code: '9861', name: '吉野家ホールディングス',              en: 'Yoshinoya' },
  { code: '9873', name: '日本KFCホールディングス',             en: 'KFC Japan' },
  { code: '7751', name: 'キヤノン',                          en: 'Canon' },
  { code: '3197', name: 'すかいらーくホールディングス',          en: 'Skylark' },
  // ── 旅行・ホテル・レジャー ────────────────────────────────
  { code: '9726', name: 'KNT-CTホールディングス',             en: 'KNT-CT' },
  { code: '9603', name: 'エイチ・アイ・エス',                  en: 'HIS' },
  { code: '9045', name: '近鉄グループホールディングス',          en: 'Kintetsu Group' },
  { code: '9008', name: '小田急電鉄',                        en: 'Odakyu Electric Railway' },
  { code: '9009', name: '京成電鉄',                          en: 'Keisei Electric Railway' },
  { code: '9005', name: '東急',                              en: 'Tokyu' },
  { code: '9006', name: '京浜急行電鉄',                       en: 'Keikyu' },
  { code: '9007', name: '小田急電鉄',                        en: 'Odakyu' },
  { code: '9048', name: '名古屋鉄道',                        en: 'Meitetsu' },
  { code: '9044', name: '南海電気鉄道',                       en: 'Nankai Electric' },
  // ── 交通・インフラ ────────────────────────────────────────
  { code: '9201', name: '日本航空',                          en: 'JAL' },
  { code: '9202', name: 'ANAホールディングス',                 en: 'ANA' },
  { code: '9020', name: '東日本旅客鉄道',                     en: 'JR East' },
  { code: '9022', name: '東海旅客鉄道',                       en: 'JR Central' },
  { code: '9021', name: '西日本旅客鉄道',                     en: 'JR West' },
  { code: '9062', name: '日本通運',                          en: 'Nippon Express' },
  { code: '9064', name: 'ヤマトホールディングス',              en: 'Yamato Holdings' },
  { code: '9065', name: '山九',                              en: 'Sankyu' },
  // ── エネルギー・石油・ガス ───────────────────────────────
  { code: '1605', name: 'INPEXコーポレーション',               en: 'INPEX' },
  { code: '5020', name: 'ENEOSホールディングス',               en: 'ENEOS Holdings' },
  { code: '9501', name: '東京電力ホールディングス',             en: 'Tokyo Electric' },
  { code: '9503', name: '関西電力',                          en: 'Kansai Electric' },
  { code: '9504', name: '中国電力',                          en: 'Chugoku Electric' },
  { code: '9505', name: '北陸電力',                          en: 'Hokuriku Electric' },
  { code: '9531', name: '東京ガス',                          en: 'Tokyo Gas' },
  { code: '9532', name: '大阪ガス',                          en: 'Osaka Gas' },
  { code: '9533', name: '東邦ガス',                          en: 'Toho Gas' },
  // ── ゲーム・エンタメ ──────────────────────────────────────
  { code: '7974', name: '任天堂',                            en: 'Nintendo' },
  { code: '9684', name: 'スクウェア・エニックス・ホールディングス', en: 'Square Enix' },
  { code: '9697', name: 'カプコン',                          en: 'Capcom' },
  { code: '7832', name: 'バンダイナムコホールディングス',        en: 'Bandai Namco' },
  { code: '2432', name: 'ディー・エヌ・エー',                  en: 'DeNA' },
  { code: '3765', name: 'ガンホー・オンライン・エンターテイメント', en: 'Gungho' },
  { code: '9766', name: 'コナミグループ',                     en: 'Konami' },
  { code: '3635', name: 'コーエーテクモホールディングス',        en: 'Koei Tecmo' },
  // ── メディア・広告 ────────────────────────────────────────
  { code: '4324', name: '電通グループ',                       en: 'Dentsu' },
  { code: '2433', name: '博報堂DYホールディングス',            en: 'Hakuhodo DY' },
  // ── 海運 ──────────────────────────────────────────────
  { code: '9101', name: '日本郵船',                          en: 'NYK Line' },
  { code: '9104', name: '商船三井',                          en: 'Mitsui OSK Lines' },
  { code: '9107', name: '川崎汽船',                          en: 'K Line' },
  // ── 人材・リクルート ──────────────────────────────────────
  { code: '6098', name: 'リクルートホールディングス',           en: 'Recruit' },
  { code: '2181', name: 'パーソルホールディングス',             en: 'Persol' },
  { code: '2148', name: 'アイティメディア',                    en: 'ITmedia' },
  // ── 防衛 ─────────────────────────────────────────────────
  { code: '7762', name: '石川製作所',                        en: 'Ishikawa Seisakusho' },
  { code: '6771', name: '池上通信機',                        en: 'Ikegami Tsushinki' },
  { code: '7603', name: 'マックハウス',                       en: 'Mac-House' },
  // ── その他主要銘柄 ─────────────────────────────────────────
  { code: '7182', name: '日本郵政',                          en: 'Japan Post Holdings' },
  { code: '2914', name: 'JT',                               en: 'Japan Tobacco' },
  { code: '4911', name: '資生堂',                            en: 'Shiseido' },
  { code: '4452', name: '花王',                              en: 'Kao' },
  { code: '4967', name: '小林製薬',                          en: 'Kobayashi Pharma' },
  { code: '4612', name: '日本ペイントホールディングス',          en: 'Nippon Paint' },
  { code: '4901', name: '富士フイルム',                       en: 'Fujifilm' },
  { code: '7912', name: '大日本印刷',                        en: 'Dai Nippon Printing' },
  { code: '7911', name: '凸版印刷',                          en: 'Toppan' },
  { code: '4046', name: '大阪ソーダ',                        en: 'Osaka Soda' },
  // ── 英数字コード銘柄（新規上場） ─────────────────────────────
  { code: '268A', name: 'リガクホールディングス',               en: 'Rigaku Holdings' },
  { code: '216A', name: 'トライアルホールディングス',            en: 'Trial Holdings' },
];
