// 主要日本株ローカルインデックス（日本語名検索用）
// コード → { 日本語名, 英語名(検索用) }
export const JP_STOCK_INDEX: Array<{ code: string; name: string; en: string }> = [
  // 半導体・電子部品
  { code: '6920', name: 'レーザーテック',               en: 'Lasertec' },
  { code: '8035', name: '東京エレクトロン',              en: 'Tokyo Electron' },
  { code: '6857', name: 'アドバンテスト',                en: 'Advantest' },
  { code: '6146', name: 'ディスコ',                     en: 'Disco' },
  { code: '6723', name: 'ルネサスエレクトロニクス',       en: 'Renesas' },
  { code: '6981', name: '村田製作所',                   en: 'Murata' },
  { code: '6594', name: 'ニデック',                     en: 'Nidec' },
  { code: '6762', name: 'TDK',                         en: 'TDK' },
  { code: '6971', name: '京セラ',                       en: 'Kyocera' },
  { code: '6861', name: 'キーエンス',                   en: 'Keyence' },
  { code: '6954', name: 'ファナック',                   en: 'Fanuc' },
  // エレクトロニクス
  { code: '6758', name: 'ソニーグループ',                en: 'Sony' },
  { code: '6752', name: 'パナソニック ホールディングス',  en: 'Panasonic' },
  { code: '6501', name: '日立製作所',                   en: 'Hitachi' },
  { code: '6502', name: '東芝',                         en: 'Toshiba' },
  { code: '6702', name: '富士通',                       en: 'Fujitsu' },
  { code: '6701', name: '日本電気',                     en: 'NEC' },
  { code: '6753', name: 'シャープ',                     en: 'Sharp' },
  { code: '7751', name: 'キヤノン',                     en: 'Canon' },
  { code: '7752', name: 'リコー',                       en: 'Ricoh' },
  { code: '7733', name: 'オリンパス',                   en: 'Olympus' },
  { code: '7741', name: 'HOYA',                        en: 'Hoya' },
  // 自動車
  { code: '7203', name: 'トヨタ自動車',                  en: 'Toyota' },
  { code: '7267', name: '本田技研工業',                  en: 'Honda' },
  { code: '7201', name: '日産自動車',                   en: 'Nissan' },
  { code: '7270', name: 'SUBARU',                      en: 'Subaru' },
  { code: '7269', name: 'スズキ',                       en: 'Suzuki' },
  { code: '7211', name: '三菱自動車工業',                en: 'Mitsubishi Motors' },
  { code: '7272', name: 'ヤマハ発動機',                  en: 'Yamaha Motor' },
  // 通信
  { code: '9984', name: 'ソフトバンクグループ',           en: 'SoftBank Group' },
  { code: '9434', name: 'ソフトバンク',                  en: 'SoftBank Corp' },
  { code: '9432', name: '日本電信電話',                  en: 'NTT' },
  { code: '9433', name: 'KDDI',                        en: 'KDDI' },
  { code: '9613', name: 'NTTデータグループ',             en: 'NTT Data' },
  // IT・インターネット
  { code: '4689', name: 'LINEヤフー',                   en: 'LINEYahoo' },
  { code: '4755', name: '楽天グループ',                  en: 'Rakuten' },
  { code: '4751', name: 'サイバーエージェント',           en: 'CyberAgent' },
  { code: '4385', name: 'メルカリ',                     en: 'Mercari' },
  { code: '2413', name: 'エムスリー',                   en: 'M3' },
  { code: '3659', name: 'ネクソン',                     en: 'Nexon' },
  { code: '9449', name: 'GMOインターネットグループ',       en: 'GMO Internet' },
  { code: '4478', name: 'フリー',                       en: 'Freee' },
  // 金融
  { code: '8306', name: '三菱UFJフィナンシャル・グループ', en: 'MUFG' },
  { code: '8316', name: '三井住友フィナンシャルグループ',  en: 'SMFG' },
  { code: '8411', name: 'みずほフィナンシャルグループ',    en: 'Mizuho' },
  { code: '8604', name: '野村ホールディングス',           en: 'Nomura' },
  { code: '8601', name: '大和証券グループ本社',           en: 'Daiwa' },
  { code: '8698', name: 'マネックスグループ',             en: 'Monex' },
  // 商社
  { code: '8001', name: '伊藤忠商事',                   en: 'Itochu' },
  { code: '8031', name: '三井物産',                     en: 'Mitsui' },
  { code: '8058', name: '三菱商事',                     en: 'Mitsubishi Corp' },
  { code: '8053', name: '住友商事',                     en: 'Sumitomo Corp' },
  { code: '8002', name: '丸紅',                         en: 'Marubeni' },
  // 小売
  { code: '9983', name: 'ファーストリテイリング',          en: 'Fast Retailing' },
  { code: '8267', name: 'イオン',                       en: 'AEON' },
  { code: '3382', name: 'セブン&アイ・ホールディングス',   en: 'Seven & i' },
  { code: '2651', name: 'ローソン',                     en: 'Lawson' },
  // 医薬品
  { code: '4502', name: '武田薬品工業',                  en: 'Takeda' },
  { code: '4503', name: 'アステラス製薬',                en: 'Astellas' },
  { code: '4523', name: 'エーザイ',                     en: 'Eisai' },
  { code: '4568', name: '第一三共',                     en: 'Daiichi Sankyo' },
  { code: '4507', name: '塩野義製薬',                   en: 'Shionogi' },
  { code: '4519', name: '中外製薬',                     en: 'Chugai' },
  { code: '4578', name: '大塚ホールディングス',           en: 'Otsuka' },
  // 素材・重工
  { code: '5401', name: '日本製鉄',                     en: 'Nippon Steel' },
  { code: '5411', name: 'JFEホールディングス',           en: 'JFE' },
  { code: '4188', name: '三菱ケミカルグループ',           en: 'Mitsubishi Chemical' },
  { code: '4063', name: '信越化学工業',                  en: 'Shin-Etsu Chemical' },
  { code: '5108', name: 'ブリヂストン',                  en: 'Bridgestone' },
  { code: '6301', name: 'コマツ',                       en: 'Komatsu' },
  { code: '7011', name: '三菱重工業',                   en: 'Mitsubishi Heavy Industries' },
  { code: '6326', name: 'クボタ',                       en: 'Kubota' },
  // 不動産
  { code: '8801', name: '三井不動産',                   en: 'Mitsui Fudosan' },
  { code: '8802', name: '三菱地所',                     en: 'Mitsubishi Estate' },
  // 食品・飲料
  { code: '2502', name: 'アサヒグループホールディングス',   en: 'Asahi' },
  { code: '2503', name: 'キリンホールディングス',          en: 'Kirin' },
  { code: '2802', name: '味の素',                       en: 'Ajinomoto' },
  { code: '2897', name: '日清食品ホールディングス',        en: 'Nissin' },
  // 交通・インフラ
  { code: '9201', name: '日本航空',                     en: 'JAL' },
  { code: '9202', name: 'ANAホールディングス',            en: 'ANA' },
  { code: '9020', name: '東日本旅客鉄道',                en: 'JR East' },
  { code: '9022', name: '東海旅客鉄道',                  en: 'JR Central' },
  { code: '9021', name: '西日本旅客鉄道',                en: 'JR West' },
  { code: '9501', name: '東京電力ホールディングス',        en: 'Tokyo Electric' },
  { code: '9503', name: '関西電力',                     en: 'Kansai Electric' },
  { code: '9531', name: '東京ガス',                     en: 'Tokyo Gas' },
  // ゲー��・エンタメ
  { code: '7974', name: '任天堂',                       en: 'Nintendo' },
  { code: '9684', name: 'スクウェア・エニックス・ホールディングス', en: 'Square Enix' },
  { code: '9697', name: 'カプコン',                     en: 'Capcom' },
  { code: '7832', name: 'バンダイナムコホールディングス',   en: 'Bandai Namco' },
  { code: '2432', name: 'ディー・エヌ・エー',             en: 'DeNA' },
  // 人材・リクルート
  { code: '6098', name: 'リクルートホールディングス',      en: 'Recruit' },
  { code: '2181', name: 'パーソルホールディングス',        en: 'Persol' },
  // その他
  { code: '7182', name: '日本郵政',                     en: 'Japan Post' },
  { code: '2914', name: 'JT',                          en: 'Japan Tobacco' },
  { code: '4911', name: '資生堂',                       en: 'Shiseido' },
];
